services:
    doctrine.coaster_listener:
            class: BddBundle\Doctrine\BuiltCoasterListener
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }

