api_platform:
    title: 'Captain Coaster API'
    description: 'Welcome to Captain Coaster API! API Keys for authentication can be found in your profile page. Contact us to get support.'
    version: '1.0.1'
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    http_cache:
        public: true
    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: [ 'Content-Type' ]
    swagger:
        api_keys:
            key:
                name: 'Authorization'
                type: 'header'
