fos_user:
    db_driver: 'orm'
    firewall_name: 'main'
    user_class: 'App\Entity\User'
    from_email:
        address: '%app_mail_from%'
        sender_name: '%app_mail_from_name%'
    service:
        mailer: fos_user.mailer.twig_swift
