hwi_oauth:
    firewall_names: [main]
    connect:
        account_connector: my.custom.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:   'facebookId'
            google:     'googleId'
    resource_owners:
        facebook:
            type: 'facebook'
            client_id: '%env(FB_ID)%'
            client_secret: '%env(FB_SECRET)%'
            infos_url: 'https://graph.facebook.com/v7.0/me?fields=id,name,email,first_name,last_name,picture'
            authorization_url: 'https://www.facebook.com/v7.0/dialog/oauth'
            access_token_url: 'https://graph.facebook.com/v7.0/oauth/access_token'
            revoke_token_url: 'https://graph.facebook.com/v7.0/me/permissions'
            scope: 'email'
            options:
                display:    'popup'
                auth_type:  'rerequest'
                csrf:       true
            paths:
                email:          'email'
                profilepicture: 'picture.data.url'
        google:
            type:                'google'
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email profile"
            options:
                csrf: true
    target_path_parameter: 'target_path'
