knp_paginator:
    page_range: 4
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'pagination/knp_custom_pagination.html.twig'
