liip_imagine:
    driver: 'imagick'
    loaders:
        default:
            filesystem:
                data_root: '%env(APP_BASE_PATH_IMAGES)%'
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        thumb_coaster:
            quality: 90
            filters:
                thumbnail: { size: [280, 210], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true }
        random_index:
            quality: 95
            filters:
                thumbnail: { size: [600, 336], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true }
        coaster_ranking:
            quality: 95
            filters:
                thumbnail: { size: [96, 96], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true }
        coaster_park_show:
            quality: 95
            filters:
                thumbnail: { size: [275, 200], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true }
