framework:
    notifier:
        chatter_transports:
            discord_notif: '%env(DISCORD_NOTIF_DSN)%'
            discord_log: '%env(DISCORD_LOG_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/discord_log']
            high: ['chat/discord_log']
            medium: ['chat/discord_log']
            low: ['chat/discord_log']
        admin_recipients:
            - { email: admin@example.com }
