twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locales: '%app_locales_array%'
        pictures_cdn: '%env(PICTURES_CDN)%'
        unities: '@App\Twig\UnitiesExtension'

when@test:
    twig:
        strict_variables: true
