version: '3.7'

services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx-captain
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
  php:
    build:
      context: ./docker/php
    container_name: php-captain
    volumes:
      - .:/var/www
      - /home/florian/projects/images:/var/www/images/coasters
  db:
    image: mariadb:10.11
    container_name: db-captain
    volumes:
      - datamaria:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
  adminer:
    image: adminer
    container_name: adminer-captain
    restart: always
    ports:
      - 8081:8080
  encore:
    image: node:16-alpine
    container_name: node-captain
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: [ "sh", "-c", "npm install && npm run build" ]
volumes:
  datamaria:
