imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BddBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    app.locales: 'fr|en'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    ide: 'phpstorm'

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: '%base_path_images%'
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumb_coaster:
            quality: 90
            filters:
                thumbnail: { size: [280, 210], mode: outbound }
        random_index:
            quality: 95
            filters:
                thumbnail: { size: [600, 336], mode: outbound }
        coaster_ranking:
            quality: 95
            filters:
                thumbnail: { size: [96, 96], mode: outbound }
        coaster_park_show:
            quality: 95
            filters:
                thumbnail: { size: [275, 200], mode: outbound }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: BddBundle\Entity\User
    from_email:
        address: "%mail_from%"
        sender_name: "%mail_from_name%"

hwi_oauth:
    connect:
        account_connector: my.custom.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:   facebookId
            google:     googleId
    firewall_names: [main]
    resource_owners:
        facebook:
            type:           'facebook'
            client_id:      '%facebook_client_id%'
            client_secret:  '%facebook_client_secret%'
            infos_url:      'https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,picture'
            scope:          'email'
            options:
                display: popup
                auth_type: rerequest
            paths:
                email:          email
                profilepicture: picture.data.url
        google:
            type:                'google'
            client_id:           '%google_client_id%'
            client_secret:       '%google_client_secret%'
            scope:               "email profile"

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true

knp_paginator:
    page_range: 20                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template