imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
        mail:
            type: fingers_crossed
            action_level: critical
            handler: deduplicated
        deduplicated:
            type:    deduplication
            time: 120
            handler: swift
        swift:
            type:       swift_mailer
            from_email: '%mail_from%'
            to_email:   '%mail_to%'
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
        discord:
            type: fingers_crossed
            action_level: error
            handler: custom_discord
        custom_discord:
            type: 'service'
            id: 'BddBundle\Service\DiscordMonologHandler'
