easy_admin:
    site_name: 'Captain Coaster'
    entities:
        Park:
            class: BddBundle\Entity\Park
            disabled_actions: ['delete']
            list:
                fields: ['id', 'name', 'coasters']
            edit:
                fields: ['name', 'website', 'country', 'latitude', 'longitude']
            new:
                fields: ['name', 'website', 'country', 'latitude', 'longitude']
        OpeningCoasters:
            class: BddBundle\Entity\Coaster
            label: 'Opening of coasters'
            disabled_actions: ['new', 'delete', 'show']
            list:
                fields:
                    - name
                    - park
                    - {property: 'status', trans: true, domain: 'database', type_options: {translation_domain: 'database'}}
                    - openingDate
                dql_filter: 'entity.openingDate < CURRENT_DATE() AND entity.status = 3'
                sort: ['openingDate', 'DESC']
            edit:
                fields:
                    - name
                    - {property: 'status', type_options: {choice_translation_domain: 'database'}}
                    - openingDate
        Images:
            class: BddBundle\Entity\Image
            label: 'Images'
            disabled_actions: ['new', 'show']
            list:
                fields:
                    - id
                    - coaster
                    - credit
                    - { property: 'enabled', type: 'toggle' }
                    - { property: 'path', type: 'image', base_path: '/images/coasters/' }
            edit:
                fields:
                    - { property: 'filename', type_options: { disabled: true } }
                    - coaster
                    - credit
                    - uploader
                    - enabled
                    - { property: 'optimized', type_options: { disabled: true } }
                    - { property: 'watermarked', type_options: { disabled: true } }
                dql_filter: 'entity.optimized = 1'
                sort: ['updatedAt', 'DESC']
            search:
                fields: ['coaster.name']
        Country:
            class: BddBundle\Entity\Country
            disabled_actions: ['delete']
            list:
                fields:
                    - name
                    - slug
            edit:
                fields:
                    - {property: 'name', type_options: {disabled: true}}
            new:
                fields: ['name', 'slug']
        Launch:
            class: BddBundle\Entity\Launch
            disabled_actions: ['delete']
            list:
                fields: ['id', 'name']
            edit:
                fields: ['name', 'slug']
            new:
                fields: ['name', 'slug']
        Manufacturer:
            class: BddBundle\Entity\Manufacturer
            disabled_actions: ['delete']
            list:
                fields: ['id', 'name', 'builtCoasters']
            edit:
                fields: ['name', 'slug', 'website', 'phoneNumber', 'place']
            new:
                fields: ['name', 'slug', 'website', 'phoneNumber', 'place']
