_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

bdd:
    resource: "@BddBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
      _locale: 'fr'