easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /{_locale}/login
    requirements:
        _locale: "%app.locales%"

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

root:
    path: "/"
    defaults: { _controller: BddBundle:Default:root }

sitemap:
    path: "/sitemap.xml"
    defaults: { _controller: BddBundle:Sitemap:index, "_format": "xml" }

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

bdd:
    resource: "@BddBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "%app.locales%"
