# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    BddBundle\:
        resource: '../../src/BddBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/BddBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    BddBundle\Controller\:
        resource: '../../src/BddBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    BddBundle\Service\ImageService:
        arguments:
            $basePath: '%base_path_images%'
            $baseUrl: '%base_url_images%'

    BddBundle\Service\ReportCoverUploader:
        arguments:
            $targetDir: '%report_cover_directory%'
            $imageManipulator: '@BddBundle\Service\ImageManipulationService'

    BddBundle\Service\ReportImageUploader:
        arguments:
            $targetDir: '%report_image_directory%'
            $imageManipulator: '@BddBundle\Service\ImageManipulationService'

    BddBundle\Service\BannerMaker:
        arguments:
            $imagine: '@liip_imagine.imagick'
            $fontPath: '%banner_font_path%'
            $targetPath: '%banner_target_path%'
            $backgroundPath: '%banner_background_path%'

    my.custom.user_provider:
        class: BddBundle\Security\Core\User\CustomUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId, google: googleId}]

    Twig\Extensions\IntlExtension:
        tags: [twig.extension]

    \HTMLPurifier:
        class: \HTMLPurifier
        public: true
