root:
    path: '/'
    controller: App\Controller\DefaultController::root

admin:
    path: /team
    controller: App\Controller\Admin\DashboardController::index

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/{_locale<en|fr|es>}'

logout:
    path: '/logout'
    controller: App\Controller\DefaultController::logout

connect_google_start:
    path: '/connect/google'
    controller: App\Controller\DefaultController::connectGoogleStart

connect_google_check:
    path: '/login/check-google'
    controller: App\Controller\DefaultController::connectGoogleCheck

sitemap:
    path: '/sitemap.xml'
    defaults: { _controller: 'App\Controller\SitemapController::indexAction', _format: 'xml' }

sitemap_image:
    path: '/sitemap_image.xml'
    defaults: { _controller: 'App\Controller\SitemapController::imageAction', _format: 'xml' }
