root:
    path: '/'
    controller: App\Controller\DefaultController::root

admin:
    path: /team
    controller: App\Controller\Admin\DashboardController::index

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/{_locale<en|fr|es>}'

logout:
    path: '/logout'
    controller: App\Controller\ConnectController::logout

connect_google_start:
    path: '/connect/google'
    controller: App\Controller\ConnectController::connectGoogleStart

connect_google_check:
    path: '/connect/google/check'
    controller: App\Controller\ConnectController::connectGoogleCheck

connect_facebook_start:
    path: '/connect/facebook'
    controller: App\Controller\ConnectController::connectFacebookStart

connect_facebook_check:
    path: '/connect/facebook/check'
    controller: App\Controller\ConnectController::connectFacebookCheck

login_check:
    path: '/login/check'
    controller: App\Controller\ConnectController::loginCheck

sitemap:
    path: '/sitemap.xml'
    controller: App\Controller\SitemapController::indexAction

sitemap_image:
    path: '/sitemap_image.xml'
    controller: App\Controller\SitemapController::imageAction
